spring.application.name=CareFinder

# ========================================
# Database
# ========================================
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_ID}
spring.datasource.password=${DATABASE_PW}

# Connection pool
spring.datasource.hikari.connection-test-query=SELECT 1
spring.datasource.hikari.maximum-pool-size=10

# ========================================
# MyBatis
# ========================================
mybatis.type-aliases-package=kr.co.ict.springboard.dto
mybatis.mapper-locations=mybatis/**/*.xml

# ========================================
# JSP
# ========================================
spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp

# ========================================
# Session
# ========================================
spring.main.banner-mode=off
server.servlet.session.timeout=30m
server.servlet.session.cookie.max-age=-1

# ========================================
# Kakao Login API
# ========================================
kakao.api_key=${KAKAO_LOGIN_KEY}
kakao.redirect_url=${KAKAO_LOGIN_URL}

# ========================================
# Naver Login API
# ========================================
naver.client.id=${NAVER_LOGIN_ID}
naver.client.secret=${NAVER_LOGIN_SECRET}
naver.redirect.uri=${NAVER_LOGIN_URI}

# ========================================
# Google Login API
# ========================================
google.oauth.client-id=${GOOGLE_LOGIN_ID}
google.oauth.client-secret=${GOOGLE_LOGIN_SECRET}
google.oauth.redirect-uri=${GOOGLE_LOGIN_URI}

# ========================================
# Google Maps API
# ========================================
google.maps.key=${GOOGLE_MAP_KEY}

# ========================================
# Kakao Maps API
# ========================================
kakao.rest-key=${KAKAO_MAP_KEY}
kakao.maps.javascript-key=${KAKAO_MAP_JS_KEY}

# ========================================
# TMAP API
# ========================================
tmap.app-key=${TMAP_KEY}

# ========================================
# Drug Dictionary API
# ========================================
drug.service-key=${DRUG_KEY}

# ========================================
# Naver News API
# ========================================
naver.news.client-id=${NAVER_NEWS_ID}
naver.news.client-secret=${NAVER_NEWS_SECRET}

# OpenAI
openai.api.key=${OPEN_AI_KEY}
openai.model=gpt-4.1-mini
